title: Switchboard Phone System
description: SwitchBoard is a corporate PBX phone system built on Asterisk. By leveraging the Asterisk Real-time capabilities, SwitchBoard can fulfill a company's phone system needs from a user-friendly web interface.

# theme: minima
remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

exclude:
  - .gitignore
  - _build.sh
